-- AUTO-GENERATED. DO NOT EDIT.
-- Source: luxury_mdb_fashion_ui_headers.xlsx
create extension if not exists citext;
create extension if not exists pg_trgm;

-- Main Categories
insert into public.catalog_main_categories (name_en) values ('Fashion') on conflict (name_en) do nothing;

-- Brands
insert into public.catalog_brands (name_en) values ('Alaïa') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Alexander McQueen') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Balenciaga') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Bally') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Balmain') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Berluti') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Bottega Veneta') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Brioni') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Brunello Cucinelli') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Burberry') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Celine') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Chanel') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Chloé') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Christian Louboutin') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Comme des Garçons') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Dior') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Dolce & Gabbana') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Dries Van Noten') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Etro') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Fendi') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Ferragamo') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Gianvito Rossi') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Giorgio Armani') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Giuseppe Zanotti') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Givenchy') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Gucci') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Hermès') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Issey Miyake') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Jil Sander') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Jimmy Choo') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Khaite') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Lanvin') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Loewe') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Loro Piana') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Louis Vuitton') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Maison Margiela') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Manolo Blahnik') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Max Mara') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Missoni') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Miu Miu') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Moncler') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Prada') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Rick Owens') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Rimowa') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Roger Vivier') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Sacai') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Saint Laurent') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Stella McCartney') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('The Row') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Thom Browne') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Tod''s') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Tom Ford') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Valentino') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Versace') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Yohji Yamamoto') on conflict (name_en) do nothing;
insert into public.catalog_brands (name_en) values ('Zegna') on conflict (name_en) do nothing;

-- Product Types
insert into public.catalog_product_types (name_en) values ('Activewear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Apres Ski') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Backpacks') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Bag Charms') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Base Layers') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Belt Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Belts') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Boots') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Cardholders') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Carry On') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Chain Wallets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Clutches and Evening Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Coats and Jackets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Coin Purses') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Compact Wallets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Crossbody Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Denim') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Dresses') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Eveningwear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Eyewear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Fashion Jewelry') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Flats and Ballet') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Fragrance') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Garment Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Gloves') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Hair Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Hats and Beanies') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Heels') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Key Holders') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Keychains') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Knitwear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Leather') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Loafers and Oxfords') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Long Wallets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Luggage') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Mid Layers') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Mini Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Mules') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Outdoor Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Outerwear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Packing Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Pants and Shorts') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Passport Covers') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Personalized Handbags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Phone Cases') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Pouches') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Sandals and Slides') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Scarves and Silks') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Shirts and Tops') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Shoulder Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Ski Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Ski Jackets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Ski Pants') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Skirts') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Skiwear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Slippers') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Sneakers') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Sunglasses') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Sweaters and Cardigans') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Swimwear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('T Shirts and Sweatshirts') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Tailoring') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Tech Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Top Handle Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Tote Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Travel Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Travel Bags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Trekking and Hiking') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Accessories') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Handbags') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Ready to Wear') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Shoes') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Ski Outdoor') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Small Leather Goods') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Travel') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('View All Wallets') on conflict (name_en) do nothing;
insert into public.catalog_product_types (name_en) values ('Weekenders') on conflict (name_en) do nothing;

-- Brand Subcategories
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alaïa'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Alexander McQueen'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balenciaga'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bally'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Balmain'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Berluti'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Travel') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Bottega Veneta'), 'Wallets') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Brioni'), 'Accessories') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Brioni'), 'Handbags') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Brioni'), 'Ready to Wear') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Brioni'), 'Shoes') on conflict (brand_id, name_en) do nothing;
insert into public.catalog_brand_subcategories (brand_id, name_en) values ((select id from public.catalog_brands where name_en = 'Brioni'), 'Small Leather Goods') on conflict (brand_id, name_en) do nothing;
